---
seed: 8
target: 'survived'
acquire:
  # Only one option may be true
  pydataset: 
    use: false
    dataset: 'titanic'
  script:
    use: true
    path: 'C:\Users\Crux\Desktop\script.py'
  sql:
    use: false
    envfile: env.py
    database: titanic_db
    query: |
      SELECT * FROM titanic_db.passengers;
  